name: release

on:
  push:
    tags:
      - '[0-9].[0-9]+.[0-9]+'

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Maven Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('./**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # extract the tag name from GITHUB_REF - e.g. refs/tags/1.0.0 --> 1.0.0
      - name: Get Tag Name
        id: get_tag_name
        run: echo ::set-output name=TAG_NAME::${GITHUB_REF#refs/tags/}

      - name: Build and Publish Docker Image
        env:
          IMAGE: philipreimer/jkube-test:${{ steps.get_tag_name.outputs.TAG_NAME }}
          USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        run: |
          - echo "${{ IMAGE }}"
          - ./mvnw --batch-mode --errors --fail-at-end --show-version --file pom.xml test jib:build -Djib.to.image="${{ IMAGE }}" -Djib.to.auth.username="${{ USERNAME }}" -Djib.to.auth.password="${{ TOKEN }}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
